services:
  db:
    image: mongo:7-jammy
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=johndoe
      - MONGO_INITDB_ROOT_PASSWORD=randompassword
      - MONGO_INITDB_DATABASE=mydb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # api:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     # Use 'db' (the service name) instead of 'localhost'
  #     - DATABASE_URL=mongodb://johndoe:randompassword@db:27017/mydb?authSource=admin
  #   volumes:
  #     - .:/app
  #     - /app/node_modules # Prevents local node_modules from overwriting container's
  #   depends_on:
  #     - db

volumes:
  mongo_data: